language: rust
rust:
  - nightly-2019-05-09

before_script: |
  rustup component add rustfmt clippy
script: |
  cargo fmt --all -- --check &&
  cargo clippy --all --all-features -- -D clippy::all &&
  cargo build --no-default-features --verbose &&
  cargo build --all --all-features --verbose &&
  cargo test --all --all-features --verbose
cache: cargo
